<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'cakephp/cakephp',
        'dev' => true,
    ),
    'versions' => array(
        'cakephp/cache' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/cache',
            'aliases' => array(),
            'reference' => '0e95a17b118d900f362de07bff902fa147e51fb2',
            'dev_requirement' => false,
        ),
        'cakephp/cakephp' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'cakephp/cakephp-codesniffer' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/cakephp-codesniffer',
            'aliases' => array(),
            'reference' => '0f3559af72fd9c2bba7310a7c4496fbb97502352',
            'dev_requirement' => true,
        ),
        'cakephp/collection' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/collection',
            'aliases' => array(),
            'reference' => '5667e755cfafe4b186f5f2a54121cf44cb86159e',
            'dev_requirement' => false,
        ),
        'cakephp/core' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/core',
            'aliases' => array(),
            'reference' => '716300a55ac86b7456e52258d3f50545545d2d6b',
            'dev_requirement' => false,
        ),
        'cakephp/database' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/database',
            'aliases' => array(),
            'reference' => 'e16dae97cfe00b1de9c210bd49f71ad5c2de199a',
            'dev_requirement' => false,
        ),
        'cakephp/datasource' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/datasource',
            'aliases' => array(),
            'reference' => 'accbe0c85552f384e587d73abdba1618c604b54d',
            'dev_requirement' => false,
        ),
        'cakephp/event' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/event',
            'aliases' => array(),
            'reference' => 'ce49dcd046ca7eb6707805c246aaeb4833b5db79',
            'dev_requirement' => false,
        ),
        'cakephp/log' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/log',
            'aliases' => array(),
            'reference' => 'cf10bdcce4e78430a780edb2cc5b4b2b4719a65d',
            'dev_requirement' => false,
        ),
        'cakephp/migrations' => array(
            'pretty_version' => '2.4.2',
            'version' => '2.4.2.0',
            'type' => 'cakephp-plugin',
            'install_path' => __DIR__ . '/../cakephp/migrations',
            'aliases' => array(),
            'reference' => '7fa4f1f8a4cd90df59cd8e3a46958c822abe457e',
            'dev_requirement' => false,
        ),
        'cakephp/orm' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/orm',
            'aliases' => array(),
            'reference' => 'bc81eba7dc47876c50410053cc6cd147017ec42c',
            'dev_requirement' => false,
        ),
        'cakephp/utility' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/utility',
            'aliases' => array(),
            'reference' => '51b0af31af3239f6141006bbd7cbc7b16aba40d6',
            'dev_requirement' => false,
        ),
        'cakephp/validation' => array(
            'pretty_version' => '3.10.5',
            'version' => '3.10.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cakephp/validation',
            'aliases' => array(),
            'reference' => '98742f8379b8010dc1d5956d6bceebfc4b60a53a',
            'dev_requirement' => false,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '1.2.18',
            'version' => '1.2.18.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => 'fe2466802556d3fe4e4d1d58ffd3ccfd0a19be0b',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.5',
            'version' => '1.4.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'reference' => 'ad4e1e23ae01b483c16f600ff1bebec184588e32',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '3.7.38',
            'version' => '3.7.38.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => '38709dc22d519a3d1be46849868aa2ddf822bcf6',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'reference' => '5794e3c5c5ba0fb037b11d8151add2a07fa82875',
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => 'b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'robmorgan/phinx' => array(
            'pretty_version' => '0.11.6',
            'version' => '0.11.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../robmorgan/phinx',
            'aliases' => array(),
            'reference' => '6bac1f51c8e35201ec281e842e6ae6dbe066212f',
            'dev_requirement' => false,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '1.5.6',
            'version' => '1.5.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'reference' => '6f3e42d311b882b25b4d409d23a289f4d3b803d5',
            'dev_requirement' => true,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'reference' => 'ed42f8f9da528d2c6cae36fe1f380b0c1d8f0658',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => '33fa45ffc81fdcc1ca368d4946da859c8cdb58d9',
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v4.4.42',
            'version' => '4.4.42.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => '815412ee8971209bd4c1eecd5f4f481eacd44bf5',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '0424dff1c58f028c451efff2045f5d92410bd540',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'fd22ab50000ef01661e2a31d850ebaa297f8e03c',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'ec444d3f3f6505bb28d11afa41e75faadebc10a1',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '77fa7995ac1b21ab60769b7323d600a991a90433',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => '3fb075789fb91f9ad9af537c4012d523085bd5af',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => 'afa00c500c2d6aea6e3b2f4862355f507bc5ebb4',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '02c1859112aa779d9ab394ae4f3381911d84052b',
            'dev_requirement' => true,
        ),
    ),
);
